echo building local default version ...
go build -o aswsg
echo building Linux/AMD64 version ...
GOOS=linux GOARCH=amd64   go build -o precompiled/aswsg_LinuxIntel64
echo building Linux/386 version ...
GOOS=linux GOARCH=386     go build -o precompiled/aswsg_linuxIntel32
echo building Linux/ARM64 version ...
GOOS=linux GOARCH=arm64   go build -o precompiled/aswsg_linuxArm64
echo building Linux/ARM version ...
GOOS=linux GOARCH=arm     go build -o precompiled/aswsg_linuxArm32
echo building Darwin/AMD64 version ...
GOOS=darwin GOARCH=amd64  go build -o precompiled/aswsg_MacIntel64
#echo building Darwin/M1 version ...
#GOOS=darwin GOARCH=m1     go build -o precompiled/aswsg_MacM1
echo building Windows/AMD64 version ...
GOOS=windows GOARCH=amd64 go build -o precompiled/aswsg_win64.exe
echo building Windows/386 version ...
GOOS=windows GOARCH=386   go build -o precompiled/aswsg_win32.exe
echo done.